
-
  branches:
   only:
   - master
  version: '{build}'
  pull_requests:
    do_not_increment_build_number: true
  nuget:
    disable_publish_on_pr: true
  build_script:
  - ps: .\Build.ps1
  test: off
  artifacts:
  - path: .\artifacts\**\*.nupkg
    name: NuGet
  deploy:
  - provider: NuGet
    server: https://www.myget.org/F/danieldziubecki/api/v2
    api_key:
      secure: zpUfg4cLMzhZOGWalOMFGSvMiNebnY6XgF7iJT39QjEZMFUolo60i2XP41QVHEGc
    skip_symbols: true
    on:
      branch: master
  - provider: NuGet
    name: production
    api_key:
      secure: FqeZ8mj1ery9QHV89WTuAJN4mtqz5iWFJ/kxwF3LKa6f3if0JmAff5lfmtdiv7x4
    on:
      branch: master
      appveyor_repo_tag: true
  

#develop
-
  branches:
      only:
      - develop
  version: '{build}'
  pull_requests:
    do_not_increment_build_number: true
  image: Ubuntu
  install:
  before_build:
    - sh: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - sh: sudo chmod +x /usr/local/bin/docker-compose
    - sh: docker-compose version
    - sh: dotnet --version
    - sh: dotnet restore ./WaitForDocker/WaitForDocker.csproj --verbosity m
  build_script:
    - sh: dotnet build ./WaitForDocker/WaitForDocker.csproj -c Release --verbosity m 
  after_build:
    - sh: dotnet test ./WaitForDocker.Tests