version: '{build}'


#develop
- 
  branches:
      only:`
      - develop
  image: Visual Studio 2017
  before_build:
    - cmd: dotnet --version
    - cmd: dotnet restore .\WaitForDocker\WaitForDocker.csproj --verbosity m
  build_script:
     - cmd: dotnet build .\WaitForDocker\WaitForDocker.csproj -c Release --verbosity m 